<?php
// $Id$

/**
* @file
* Installation options for TableField
*/

/*
* Implementation of hook_install().
*/
function tablefield_install() {
}

/**
* Implementation of hook_uninstall().
*/
function tablefield_uninstall() {
}

/**
* Implementation of hook_enable().
*
* Notify content module when this module is enabled.
*/
function tablefield_enable() {
}

/**
* Implementation of hook_disable().
*
* Notify content module when this module is disabled.
*/
function tablefield_disable() {
}
?>
